#manifest:
#  remotes:
    # zmk official
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
      # bravekarma
#    - name: caksoylar
#      url-base: https://github.com/caksoylar
      # kyek / duckyb
#    - name: duckyb
#      url-base: https://github.com/duckyb
#  projects:
#    - name: zmk
#      remote: zmkfirmware
#      revision: main
#      import: app/west.yml
#    - name: urchin-zmk-module
#      remote: duckyb
#      revision: main
#  self:
#    path: config

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-with-input-processors
      import: app/west.yml
  self:
    path: config
